### ISSUE TITLE
What is this file?

### ISSUE THREAD

**Issue by CosignCosine** [KhanAcademyAmateurs/UsefulKAScripts#1]
https://github.com/KhanAcademyAmateurs/UsefulKAScripts/blob/master/next-eval.scpt

**Comment by 1kq2lo40lozpmb63** [comment]
Read the [README](https://github.com/KhanAcademyAmateurs/UsefulKAScripts/blob/master/README.md)

**Comment by CosignCosine** [comment]
OK, thanks!
